#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const util = require('util')
const mkdirp = require('mkdirp')
const axios = require('axios')
const cheerio = require('cheerio')

const readFile = util.promisify(fs.readFile)

const URLS_FILE = './urls.txt'

;(async () => {
    try {
        const urls = (await readFile(URLS_FILE, 'utf8')).trim().split('\n')
        await Promise.all(urls.map(doIt))
        console.log('All done')
    } catch (e) {
        console.error(e)
    }
})()

async function doIt(url) {
    const response = await axios(url)
    const data = extractData(response.data)
    const dir = `./output/${data.name}`
    await mkdirp(dir)
    const images = await downloadImages(dir, data)
    console.log(`Finished downloading images for ${data.name}`)
    return images
}

function extractData(html) {
    const $ = cheerio.load(html)
    const name = $('.new-product-page-name').text()
    const imageUrls = $('.panel-image img').map((i, el) => $(el).attr('src')).get()
    // Assume first image found is the cover image
    const coverImage = imageUrls[0]
    return { name, coverImage, imageUrls }
}

async function downloadImage(outputDir, url, cover=false) {
    const response = await axios({ url, responseType: 'stream' })
    const coverPrefix = cover ? 'cover-' : ''
    const filename = path.join(outputDir, coverPrefix + path.basename(url))
    return new Promise((resolve, reject) => {
        response.data
                .pipe(fs.createWriteStream(filename))
                .on('finish', () => resolve(filename))
                .on('error', e => reject(e))
    })
}

async function downloadImages(dir, { coverImage, imageUrls }) {
    return Promise.all(
        imageUrls.map(url => downloadImage(dir, url, url === coverImage))
    )
}
